[default]
test = "test"
out = "artifacts"
optimizer = true
optimizer_runs = 200
solc-version = "0.8.10"
verbosity = 1
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/'
]
# eth-rpc-url = "https://mainnet.infura.io"

# See more config options https://github.com/gakonst/foundry/tree/master/config
